engines:
  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess:
        enabled: false
      Naming/ShortMethodName:
        enabled: false     
      Naming/ShortVariable:
        enabled: false
      Controversial/Superglobals:
        enabled: false
ratings:    
    paths:
    - "classes/**"
    - "boosts/**"
    - "config/**"
exclude_paths:
- "tests/"
